/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.0.2/samples
 */
plugins {
    java
    application
}

repositories {
    mavenCentral()
}

application {
    mainClass.set("simplejavatexteditor.SimpleJavaTextEditor")
}

java {

    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}